### ISSUE TITLE
create..Validator.init() got an unexpected keyword argument 'registry'

### ISSUE THREAD

**Issue by ftorradeflot** [rucio/jupyterlab-extension#37]
When testing the integration of the jupyterlab 4 version of the extension in the VRE environment, this error was encountered:

│ notebook WARNING: Use start-notebook.py instead │ 
│ notebook Traceback (most recent call last): │ 
│ notebook File "/opt/conda/bin/jupyterhub-singleuser", line 6, in │
│ notebook from jupyterhub.singleuser import main │ 
│ notebook File "/opt/conda/lib/python3.11/site-packages/jupyterhub/singleuser/init.py", line 66, in │
│ notebook from .extension import main │ 
│ notebook File "/opt/conda/lib/python3.11/site-packages/jupyterhub/singleuser/extension.py", line 36, in │ 
│ notebook from jupyter_server.auth.logout import LogoutHandler │ 
│ notebook File "/opt/conda/lib/python3.11/site-packages/jupyter_server/auth/logout.py", line 5, in │ 
│ notebook from ..base.handlers import JupyterHandler │ 
│ notebook File "/opt/conda/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 24, in │ 
│ notebook from jupyter_events import EventLogger │ 
│ notebook File "/opt/conda/lib/python3.11/site-packages/jupyter_events/init.py", line 3, in │ 
│ notebook from .logger import EVENTS_METADATA_VERSION, EventLogger │ 
│ notebook File "/opt/conda/lib/python3.11/site-packages/jupyter_events/logger.py", line 19, in │ 
│ notebook from .schema import SchemaType │ 
│ notebook File "/opt/conda/lib/python3.11/site-packages/jupyter_events/schema.py", line 18, in │ 
│ notebook from .validators import draft7_format_checker, validate_schema │ 
│ notebook File "/opt/conda/lib/python3.11/site-packages/jupyter_events/validators.py", line 44, in │
│ notebook JUPYTER_EVENTS_SCHEMA_VALIDATOR = Draft7Validator( │ 
│ notebook ^^^^^^^^^^^^^^^^ │ 
│ notebook TypeError: create..Validator.init() got an unexpected keyword argument 'registry' │ 
│ Stream closed EOF for jhub-dev/jupyter-garcia (notebook)

**Comment by ftorradeflot** [comment]
We initially thought there migh be some API change in jsonschema from versions 4.18 to 4.20-22, but this is not the case.

When inspecting the docker image generated by the [action in the VRE environments repository](https://github.com/vre-hub/environments/actions/runs/9114185421) we see that it contains jsonschema==3.2.0 . In this version of the library the Draft7Validator does not include a registry argument.

The problem comes from the [installation of the reana-client](https://github.com/vre-hub/environments/blob/00447f23cb91bbb55f403afa7e39ec11baf7e884/vre-singleuser-py311/Dockerfile#L38) : reana-client -> reana-commons -> jsonschema[format]>=3.0.1,<4.0.0

When building the VRE image, conda/mamba and pip are used indistinctly, which breaks the dependencies.

The problem does not come from the extension, but from the REANA libraries, that should be updated.
